version: '3.9'

services:
  postgres-product:
    image: postgres:17-alpine
    container_name: postgres-product
    restart: unless-stopped
    ports:
      - "${PRODUCT_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-product:
    image: redis:7-alpine
    container_name: redis-product
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_product_data:
