spring:
  application:
    name: product-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${PRODUCT_DB_USER}
    password: ${PRODUCT_DB_PASSWORD}

  jpa:
    hibernate:
    ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
